language: php

services:
  - mysql

before_install:
  - composer --version

before_script:
  - mysql -u root -e "CREATE DATABASE night;"
  - mysql -u root -e "CREATE USER 'night'@'localhost' IDENTIFIED BY 'night';"
  - mysql -u root -e "GRANT ALL ON night.* TO 'night'@'localhost';"
  - mysql -u root night < content/sql/night-sky.sql

php:
  - '7.4'
  - '8.1'
  - '8.2'
  - nightly

matrix:
  allow_failures:
    - php: nightly

script: phpunit content/tests/TestsMain.php
