language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE night;"
  - mysql -u root -e "CREATE USER 'night'@'localhost' IDENTIFIED BY 'night';"
  - mysql -u root -e "GRANT ALL ON night.* TO 'night'@'localhost';"
  - mysql -u root night < content/sql/night-sky.sql
  - php -v

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 8.0

script: phpunit content/tests/TestsMain.php
