language: php

services:
  - mysql

before_install:
  - php -v
  - composer --version

before_script:
  - mysql -u root -e "CREATE DATABASE night;"
  - mysql -u root -e "CREATE USER 'night'@'localhost' IDENTIFIED BY 'night';"
  - mysql -u root -e "GRANT ALL ON night.* TO 'night'@'localhost';"
  - mysql -u root night < content/sql/night-sky.sql

php:
  - '7.4'
  - '8.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 8.2
      dist: jammy # Version 8.2 is not available in the "bionic", newer version is required.
      addons:
        apt:
          packages:
            - "libonig5" # This library is required, since Travis fails to properly install & run the PHP 8.2

script: phpunit content/tests/TestsMain.php
